# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e7550ff20d7bdcf723251d6907c78062bba5b429d6074aa94b0f5d031140e36ce73923788accf4a04d6d33dcc87d9ffe1b7286b295f8ae88b854b327b81a5a3

test:
  secret_key_base: cb75cc35ae9788a76c6f958061b2059a2216d8dcddae35c899ae7a71e2f0a38d09706ce3b342fe14df4a45539a456acf700998a30f1f92510ce63c5d627a04e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
